/*
 * Gropify - A type-safe and modern properties plugin for Gradle.
 * Copyright (C) 2019 HighCapable
 * https://github.com/HighCapable/Gropify
 *
 * Apache License Version 2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is created by fankes on 2025/10/11.
 */
package com.highcapable.gropify.plugin.generator

import com.highcapable.gropify.debug.error
import com.highcapable.gropify.plugin.Gropify
import com.highcapable.gropify.plugin.config.proxy.GropifyConfig
import com.highcapable.gropify.plugin.generator.config.GenerateConfig
import com.highcapable.gropify.plugin.generator.config.SourceCodeSpec
import com.highcapable.gropify.plugin.generator.extension.PropertyMap
import com.highcapable.gropify.plugin.generator.extension.escapeForJavaPoet
import com.highcapable.gropify.plugin.generator.extension.toOptimize
import com.highcapable.gropify.plugin.generator.extension.toUnderscores
import com.highcapable.gropify.utils.extension.firstNumberToLetter
import com.palantir.javapoet.ClassName
import com.palantir.javapoet.FieldSpec
import com.palantir.javapoet.JavaFile
import com.palantir.javapoet.TypeSpec
import javax.lang.model.element.Modifier

/**
 * Generator for Java code.
 */
internal class JavaCodeGenerator {

    /**
     * Build Java source code.
     * @return [SourceCodeSpec]
     */
    fun build(config: GropifyConfig.CommonCodeGenerateConfig, generateConfig: GenerateConfig, keyValues: PropertyMap) = runCatching {
        val className = ClassName.get(generateConfig.packageName, generateConfig.className)

        val typeSpec = TypeSpec.classBuilder(className).apply {
            addJavadoc(
                """
                  This class is auto generated by Gropify.
                  <br/>
                  You can visit <a href="${Gropify.PROJECT_URL}">here</a> for more help.
                """.trimIndent()
            )

            if (!config.isRestrictedAccessEnabled) addModifiers(Modifier.PUBLIC)
            keyValues.toOptimize().toUnderscores().forEach { (key, value) ->
                val currentKey = value.first
                val currentValue = value.second

                addField(
                    FieldSpec.builder(currentValue.type.java, key.firstNumberToLetter()).apply {
                        addJavadoc("Resolve the \$S value \$S.", currentKey, currentValue.raw)

                        if (!config.isRestrictedAccessEnabled)
                            addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                        else addModifiers(Modifier.STATIC, Modifier.FINAL)

                        initializer(currentValue.codeValue.escapeForJavaPoet())
                    }.build()
                )
            }
        }.build()

        val javaFile = JavaFile.builder(generateConfig.packageName, typeSpec).apply {
            addFileComment(
                """
                  This file is auto generated by Gropify.
                  You can visit ${Gropify.PROJECT_URL} for more help.
                  **DO NOT EDIT THIS FILE MANUALLY**
                """.trimIndent()
            )
        }.build()
        SourceCodeSpec(SourceCodeSpec.Type.Java, javaFile)
    }.getOrElse { Gropify.error("Failed to generated Java file.\n${it.stackTraceToString()}") }
}