/*
 * Gropify - A type-safe and modern properties plugin for Gradle.
 * Copyright (C) 2019 HighCapable
 * https://github.com/HighCapable/Gropify
 *
 * Apache License Version 2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * This file is created by fankes on 2025/10/11.
 */
package com.highcapable.gropify.plugin.generator

import com.highcapable.gropify.internal.error
import com.highcapable.gropify.plugin.Gropify
import com.highcapable.gropify.plugin.config.proxy.GropifyConfig
import com.highcapable.gropify.plugin.generator.config.GenerateConfig
import com.highcapable.gropify.plugin.generator.config.SourceCodeSpec
import com.highcapable.gropify.plugin.generator.extension.PropertyMap
import com.highcapable.gropify.plugin.generator.extension.toOptimize
import com.highcapable.gropify.plugin.generator.extension.toPoetNoEscape
import com.highcapable.gropify.plugin.generator.extension.toPoetSpace
import com.highcapable.gropify.plugin.generator.extension.toUnderscores
import com.highcapable.gropify.utils.extension.firstNumberToLetter
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec

/**
 * Generator for Kotlin code.
 */
internal class KotlinCodeGenerator {

    /**
     * Build Kotlin source code.
     * @return [SourceCodeSpec]
     */
    fun build(config: GropifyConfig.CommonCodeGenerateConfig, generateConfig: GenerateConfig, keyValues: PropertyMap) = runCatching {
        val fileSpec = FileSpec.builder(generateConfig.packageName, generateConfig.className).apply {
            addType(TypeSpec.objectBuilder(generateConfig.className).apply {
                addFileComment(
                    """
                      This file is auto generated by Gropify.
                      You can visit ${Gropify.PROJECT_URL} for more help.
                      **DO NOT EDIT THIS FILE MANUALLY**
                    """.trimIndent()
                )
                addKdoc(
                    """
                      This class is auto generated by Gropify.
                      You can visit [here](${Gropify.PROJECT_URL}) for more help.
                    """.trimIndent()
                )

                if (config.isRestrictedAccessEnabled) addModifiers(KModifier.INTERNAL)
                keyValues.toOptimize().toUnderscores().forEach { (key, value) ->
                    val currentKey = value.first
                    val currentValue = value.second

                    addProperty(PropertySpec.builder(key.firstNumberToLetter(), currentValue.type).apply {
                        addKdoc("Resolve the \"${currentKey.toPoetNoEscape()}\" value \"${currentValue.raw.toPoetNoEscape()}\".")

                        if (config.isRestrictedAccessEnabled) addModifiers(KModifier.INTERNAL)
                        addModifiers(KModifier.CONST)
                        initializer(currentValue.codeValue.toPoetNoEscape().toPoetSpace())
                    }.build())
                }
            }.build())
        }.build()

        SourceCodeSpec(SourceCodeSpec.Type.Kotlin, fileSpec)
    }.getOrElse { Gropify.error("Failed to generated Kotlin file.\n$it") }
}